### ISSUE TITLE
panic serving 127.0.0.1:1913: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by coandco** [falcosecurity/falcosidekick-ui#94]
**Describe the bug**
I'm attempting to run falcosidekick-ui using the official Docker image, with this invocation:
```
docker run --net=host falcosecurity/falcosidekick-ui -t 604800 -r localhost:30003
```
(where localhost:30003 is my local Redisearch-enabled Redis instance)

As soon as I load the UI in the browser, the console is spammed over and over with errors like these:
```
echo: http: panic serving 127.0.0.1:1913: interface conversion: interface {} is nil, not string
goroutine 590 [running]:
net/http.(*conn).serve.func1()
        go/src/net/http/server.go:1825 +0xbf
panic({0x94e1c0, 0xc0024d19e0})
        go/src/runtime/panic.go:844 +0x258
github.com/falcosecurity/falcosidekick-ui/internal/database/redis.SearchKey(0xc00041d748?, 0xc0006b5a40)
        /home/circleci/project/internal/database/redis/search.go:20 +0x475
github.com/falcosecurity/falcosidekick-ui/internal/events.Search(0x9d75e0?)
        /home/circleci/project/internal/events/search.go:11 +0x4a
github.com/falcosecurity/falcosidekick-ui/internal/api.Search({0xac1320, 0xc0006b59a0})
        /home/circleci/project/internal/api/api.go:120 +0x228
github.com/labstack/echo/v4/middleware.BasicAuthWithConfig.func1.1({0xac1320, 0xc0006b59a0})
        pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/basic_auth.go:93 +0x4a5
github.com/labstack/echo/v4.(*Echo).add.func1({0xac1320, 0xc0006b59a0})
        pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x51
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0005d2000, {0xabdd68?, 0xc00010b0a0}, 0xc001ad9100)
        pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x3bc
net/http.serverHandler.ServeHTTP({0xc0024d0750?}, {0xabdd68, 0xc00010b0a0}, 0xc001ad9100)
        go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc001afc3c0, {0xabe140, 0xc0005e1650})
        go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        go/src/net/http/server.go:3071 +0x4db
```

I'm not sure what to make of this, but it doesn't seem like intended behavior.

**How to reproduce it**

1. Run the docker invocation above: `docker run --net=host falcosecurity/falcosidekick-ui -t 604800 -r localhost:30003`
2. Access http://localhost:2802 in a browser and log in.  The spam will start immediately.

**Expected behaviour**

I'd expect there not to be huge amounts of go panics on the console when basic actions like looking at the main dashboard are taken.

**Screenshots**

**Environment**

- Falco version: 0.33.1
- System info:
```
{
  "machine": "x86_64",
  "nodename": "dev",
  "release": "5.10.0-18-amd64",
  "sysname": "Linux",
  "version": "#1 SMP Debian 5.10.140-1 (2022-09-02)"
}
```
- Cloud provider or hardware configuration: bare metal
- OS: Debian GNU/Linux 11 (bullseye)
- Kernel: Linux dev 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
- Installation method: from source

**Additional context**

**Comment by coandco** [comment]
Turned out it was an artifact of the way my Redis server was set up.  When I ran it with docker-compose and a proper redis-stack server, things worked fine.
